name: the fig rig
favicon: null
layout_spectrum: 0.42510444833897054
typography_spectrum: 0.7740187507588416
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d4d4d4'
    - '#cd7627'
    - '#000000'
    - '#4d4d4d'
  brandStrength: 0.7372730353381485
  lightness: 0.14789096801541746
  saturation: 0.5663546759169549
  rhythmicContrast: 0.8673461109865457
purpose: []
